name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: create sbt directory
      run: mkdir -p ~/.sbt/1.0

    - name: add Artima repository
      run: echo "resolvers += \"Artima Maven Repository\" at \"http://repo.artima.com/releases\"" > ~/.sbt/1.0/global.sbt

    - name: Download Snapshot of Tester2
      run: git clone https://github.com/ucb-bar/chisel-testers2.git

    - name: Publish Local Tester2
      run: cd chisel-testers2 && sbt publishLocal

    - name: Download Snapshot of CSP
      run: git clone https://github.com/parzival3/csp.git

    - name: Publish Local csp
      run: cd csp && sbt publishLocal

    - name: install Verilator
      run: sudo apt update && sudo apt-get install verilator

    - name: Run tests
      run: |
        sbt clean coverage test
        sbt test

    - name: Create Coverage Report
      run: sbt coverageReport

    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_SECRET }}

    - name: Change base-tag in index.html from / to Coverage
      run: sed -i 's/<base href="\/" \/>/<base href="\/Coverage\/" \/>/g' output/index.html

      # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp output/index.html output/404.html

    - name: Commit output to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: output
