name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: create sbt directory
      run: mkdir -p ~/.sbt/1.0

    - name: install Verilator
      run: sudo apt update && sudo apt-get install verilator

    - name: add Artima repository
      run: echo "resolvers += \"Artima Maven Repository\" at \"http://repo.artima.com/releases\"" > ~/.sbt/1.0/global.sbt

    - name: Run tests
      run:  sbt clean coverage test

    - name: Create Coverage Report
      run: sbt coverageReport

    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_SECRET }}
      
    - name: Commit output to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: output
